CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    product_sku VARCHAR(20) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    movement_type VARCHAR(30) NOT NULL CHECK (movement_type IN
        ('OPENING', 'SALE', 'SALE_REVERSAL', 'RESTOCK', 'CORRECTION', 'DAMAGE', 'PRODUCT_DELETED')),
    quantity_change INTEGER NOT NULL,
    stock_before INTEGER NOT NULL CHECK (stock_before >= 0),
    stock_after INTEGER NOT NULL CHECK (stock_after >= 0),
    reason VARCHAR(500) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT stock_movement_balance CHECK (stock_after = stock_before + quantity_change)
);

CREATE INDEX idx_stock_movements_recent ON stock_movements (created_at DESC, id DESC);
CREATE INDEX idx_stock_movements_product ON stock_movements (product_id, created_at DESC, id DESC);

-- The application uses its authenticated Spring API, not the Supabase Data API.
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;

-- Existing stock has no reconstructible history. Start an honest opening balance.
INSERT INTO stock_movements
    (product_id, product_sku, product_name, movement_type, quantity_change,
     stock_before, stock_after, reason, actor)
SELECT id, sku, name, 'OPENING', stock, 0, stock,
       'Opening balance when stock history was enabled', 'system'
FROM products;
