CREATE TABLE tank_exchanges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL UNIQUE REFERENCES sales(id) ON DELETE RESTRICT,
    customer_tank_product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    supplied_tank_product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    customer_tank_name VARCHAR(255) NOT NULL,
    customer_tank_sku VARCHAR(20) NOT NULL,
    supplied_tank_name VARCHAR(255) NOT NULL,
    supplied_tank_sku VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tank_exchanges_recent ON tank_exchanges (created_at DESC, id DESC);
ALTER TABLE tank_exchanges ENABLE ROW LEVEL SECURITY;
